#!/bin/bash

###############################################################################
# Environment Variables
###############################################################################
export DJANGO_DEBUG="True"
export DJANGO_SETTINGS_MODULE=keeper.settings.development
export HISTSIZE=10000
export HISTCONTROL=erasedups
shopt -s histappend
export HISTTIMEFORMAT="%h/%d - %H:%M:%S "
export HOSTFILE="$HOME/.hosts"
export NODE_INSTALL=/usr/local/bin/node
export NODE_PATH=/usr/local/bin
export win=/mnt/c/Users/mrmag/

export DISPLAY=:0
export DOCKER_HOST=localhost:2375

alias pbcopy='clip.exe'
alias pbpaste='powershell.exe Get-Clipboard'

export PATH="$PATH:/usr/bin:$HOME/bin"
#export PATH="$PATH:$HOME/Scripts/Python" #add custom python scripts

export CLICOLOR=1
export PS1="\e]0;\h \w\007 \d \t \u@\[\e[1;33m\]\h\[\e[0m\]: \w\n\$ "
export LESS='FiX'

export PATH="/mnt/c/Users/mrmag/Projects/selenium:$PATH"

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi
